<script setup lang="ts">
import { computed, ref } from 'vue'
import { BadgeCheck, Check, ChevronDown, CreditCard, Crown, ShieldCheck, Sparkles, X } from 'lucide-vue-next'

type PlanKey = 'free' | 'plus' | 'pro'
interface Plan { key: PlanKey; name: string; monthlyPrice: number; description: string; features: string[]; featured?: boolean }

const billingCycle = ref<'monthly' | 'yearly'>('monthly')
const currentPlan = ref<PlanKey>('free')
const selectedPlan = ref<PlanKey | null>(null)
const cardHolder = ref('')
const cardNumber = ref('')
const expiry = ref('')
const cvc = ref('')
const agreed = ref(false)
const plans: Plan[] = [
  { key: 'free', name: 'Free', monthlyPrice: 0, description: '剛開始管理出租物件所需要的基本工具。', features: ['最多 1 個物件', '最多 5 間房間', '租客與租約管理', '基本收支紀錄'] },
  { key: 'plus', name: 'Plus', monthlyPrice: 299, description: '讓日常管理更省時，適合成長中的房東。', features: ['最多 5 個物件', '最多 30 間房間', '租金到期提醒', '維修工單與進度追蹤', '匯出收支報表'], featured: true },
  { key: 'pro', name: 'Pro', monthlyPrice: 599, description: '完整的營運協作功能，專為專業出租管理而設。', features: ['不限物件與房間數', '多人團隊協作', '自訂通知與權限', '進階營運報表', '優先客服支援'] },
]
const selectedPlanInfo = computed(() => plans.find(plan => plan.key === selectedPlan.value))
const price = (plan: Plan) => billingCycle.value === 'yearly' ? Math.round(plan.monthlyPrice * 0.83) : plan.monthlyPrice
const cycleLabel = computed(() => billingCycle.value === 'yearly' ? '年繳（每月）' : '月繳')
const canPay = computed(() => Boolean(cardHolder.value && cardNumber.value.replace(/\s/g, '').length === 16 && expiry.value.length === 5 && cvc.value.length >= 3 && agreed.value))
function choosePlan(plan: Plan) { if (plan.key === 'free') { currentPlan.value = 'free'; selectedPlan.value = null; return }; selectedPlan.value = plan.key }
function completePayment() { if (selectedPlan.value && canPay.value) { currentPlan.value = selectedPlan.value; selectedPlan.value = null } }
function formatCardNumber() { cardNumber.value = cardNumber.value.replace(/\D/g, '').slice(0, 16).replace(/(\d{4})(?=\d)/g, '$1 ') }
function formatExpiry() { const value = expiry.value.replace(/\D/g, '').slice(0, 4); expiry.value = value.length > 2 ? `${value.slice(0, 2)}/${value.slice(2)}` : value }
</script>

<template>
  <div class="subscription-page mx-auto max-w-[1440px] space-y-6">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[#68846d]">Plan & billing</p><h1 class="text-3xl font-black tracking-tight sm:text-4xl">方案與訂閱</h1><p class="mt-2 text-sm text-[#778078]">選擇最適合目前出租規模的方案，隨時可以升級或調整。</p></div><div class="current-plan-card"><span><BadgeCheck class="h-5 w-5" /></span><div><small>目前方案</small><strong>{{ plans.find(plan => plan.key === currentPlan)?.name }}</strong></div><em>啟用中</em></div></header>
    <section class="hero"><div><span class="eyebrow"><Sparkles class="h-3.5 w-3.5" /> RentMate for landlords</span><h2>把繁瑣管理，留給更聰明的工具。</h2><p>所有方案都包含安全的資料保存與租客管理功能。年繳可節省約 17%，方案升級即時生效。</p></div><div class="billing-toggle"><button :class="{ active: billingCycle === 'monthly' }" @click="billingCycle = 'monthly'">月繳</button><button :class="{ active: billingCycle === 'yearly' }" @click="billingCycle = 'yearly'">年繳 <b>省 17%</b></button></div></section>
    <section class="grid gap-5 lg:grid-cols-3"><article v-for="plan in plans" :key="plan.key" class="plan-card" :class="{ featured: plan.featured, current: currentPlan === plan.key }"><div v-if="plan.featured" class="popular"><Crown class="h-3.5 w-3.5" /> 最受歡迎</div><div class="flex items-start justify-between gap-3"><div><h2>{{ plan.name }}</h2><p>{{ plan.description }}</p></div><span class="plan-icon" :class="plan.key"><Sparkles v-if="plan.key !== 'free'" class="h-4 w-4" /><ShieldCheck v-else class="h-4 w-4" /></span></div><div class="price"><strong>{{ plan.monthlyPrice ? `NT$ ${price(plan).toLocaleString()}` : '免費' }}</strong><span v-if="plan.monthlyPrice">／月</span></div><p class="yearly-note">{{ plan.monthlyPrice && billingCycle === 'yearly' ? `年繳 NT$ ${(price(plan) * 12).toLocaleString()}，已含優惠` : plan.monthlyPrice ? cycleLabel : '永久免費使用' }}</p><button class="plan-action" :class="{ selected: currentPlan === plan.key }" @click="choosePlan(plan)"><Check v-if="currentPlan === plan.key" class="h-4 w-4" />{{ currentPlan === plan.key ? '目前使用中' : plan.key === 'free' ? '切換至 Free' : `選擇 ${plan.name}` }}</button><ul><li v-for="feature in plan.features" :key="feature"><Check class="h-4 w-4" />{{ feature }}</li></ul></article></section>
    <section class="included-card"><div><ShieldCheck /><span><b>所有方案均受保護</b><small>採用加密傳輸與安全付款機制，保障帳務與出租資料。</small></span></div><button>常見問題 <ChevronDown class="inline h-4 w-4" /></button></section>
    <div v-if="selectedPlan && selectedPlanInfo" class="fixed inset-0 z-50 grid place-items-center bg-[#233129]/45 p-4" @click.self="selectedPlan = null"><section class="payment-dialog"><button class="close-button" aria-label="關閉付款視窗" @click="selectedPlan = null"><X class="h-5 w-5" /></button><div class="payment-heading"><span><CreditCard class="h-5 w-5" /></span><div><p>安全付款</p><h2>訂閱 {{ selectedPlanInfo.name }} 方案</h2></div></div><div class="payment-summary"><span>{{ selectedPlanInfo.name }} · {{ cycleLabel }}</span><strong>NT$ {{ price(selectedPlanInfo).toLocaleString() }}<small>／月</small></strong></div><form class="space-y-4" @submit.prevent="completePayment"><label>持卡人姓名<input v-model="cardHolder" autocomplete="cc-name" placeholder="王小明" /></label><label>卡號<div class="input-icon"><CreditCard class="h-4 w-4" /><input v-model="cardNumber" inputmode="numeric" autocomplete="cc-number" maxlength="19" placeholder="1234 5678 9012 3456" @input="formatCardNumber" /></div></label><div class="grid grid-cols-2 gap-3"><label>有效期限<input v-model="expiry" inputmode="numeric" autocomplete="cc-exp" maxlength="5" placeholder="MM/YY" @input="formatExpiry" /></label><label>安全碼<input v-model="cvc" inputmode="numeric" autocomplete="cc-csc" maxlength="3" placeholder="CVC" /></label></div><label class="agreement"><input v-model="agreed" type="checkbox" />我同意服務條款與自動續訂規則。</label><button class="pay-button" type="submit" :disabled="!canPay">確認付款 NT$ {{ price(selectedPlanInfo).toLocaleString() }}</button></form><p class="payment-note"><ShieldCheck class="h-3.5 w-3.5" /> 此為付款介面示範，不會實際扣款。</p></section></div>
  </div>
</template>

<style scoped>
@reference "../../index.css";
.current-plan-card { @apply flex items-center gap-3 rounded-2xl border border-[#dfd9cc] bg-white/80 px-4 py-3; }.current-plan-card>span { @apply grid h-10 w-10 place-items-center rounded-xl bg-[#e5f1e5] text-[#55775c]; }.current-plan-card small,.current-plan-card strong { @apply block; }.current-plan-card small { @apply text-xs text-[#7d877e]; }.current-plan-card strong { @apply mt-0.5 text-sm; }.current-plan-card em { @apply ml-2 rounded-full bg-[#e7f2e8] px-2 py-1 text-[11px] font-bold not-italic text-[#52775a]; }
.hero { @apply flex flex-col justify-between gap-6 rounded-[1.7rem] border border-[#dbe4d8] bg-[linear-gradient(120deg,#eef5ed,#fbfaf5_62%,#f0eee4)] px-5 py-7 sm:px-9 sm:py-9 md:flex-row md:items-end; }.eyebrow { @apply inline-flex items-center gap-1.5 rounded-full bg-white/80 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.12em] text-[#56775b]; }.hero h2 { @apply mt-3 text-2xl font-black tracking-tight sm:text-3xl; }.hero p { @apply mt-2 max-w-2xl text-sm leading-6 text-[#637166]; }.billing-toggle { @apply flex shrink-0 rounded-xl border border-[#d9dfd4] bg-white/75 p-1; }.billing-toggle button { @apply rounded-lg px-3 py-2 text-xs font-bold text-[#788078] transition sm:px-4; }.billing-toggle button.active { @apply bg-[#5b8263] text-white shadow-sm; }.billing-toggle b { @apply ml-1 rounded-full bg-[#e4f1e5] px-1.5 py-0.5 text-[10px] text-[#52745a]; }.billing-toggle .active b { @apply bg-white/20 text-white; }
.plan-card { @apply relative overflow-hidden rounded-[1.5rem] border border-[#e2dccf] bg-white/85 p-6 shadow-[0_8px_22px_rgba(66,72,60,.04)]; }.plan-card.featured { @apply border-[#7d9b81] bg-[#fcfdf9] shadow-[0_16px_32px_rgba(76,112,83,.13)]; }.plan-card.current { @apply ring-2 ring-[#bed4c0]; }.popular { @apply absolute right-0 top-0 flex items-center gap-1 rounded-bl-xl bg-[#5b8263] px-3 py-1.5 text-[11px] font-bold text-white; }.plan-card h2 { @apply text-2xl font-black tracking-tight; }.plan-card p { @apply mt-2 min-h-10 text-sm leading-5 text-[#788079]; }.plan-icon { @apply grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf1e9] text-[#65736a]; }.plan-icon.plus { @apply bg-[#e4f1e5] text-[#52775a]; }.plan-icon.pro { @apply bg-[#f2eadc] text-[#9a6b2d]; }.price { @apply mt-7 flex items-end gap-1; }.price strong { @apply text-3xl font-black tracking-tight; }.price span { @apply mb-1 text-sm text-[#7d857e]; }.plan-card .yearly-note { @apply mt-1 min-h-5 text-xs text-[#719075]; }.plan-action { @apply mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-[#bcd1be] bg-white py-3 text-sm font-bold text-[#53765a] transition hover:bg-[#edf5ed]; }.plan-action.selected { @apply border-[#5b8263] bg-[#5b8263] text-white; }.plan-card ul { @apply mt-6 space-y-3 border-t border-[#ece7dc] pt-5; }.plan-card li { @apply flex items-center gap-2 text-sm text-[#58645b]; }.plan-card li svg { @apply shrink-0 text-[#5e8965]; }
.included-card { @apply flex flex-col gap-4 rounded-[1.3rem] border border-[#e2dccf] bg-white/70 p-5 sm:flex-row sm:items-center sm:justify-between; }.included-card>div { @apply flex items-center gap-3; }.included-card>div>svg { @apply h-10 w-10 rounded-xl bg-[#e7f2e8] p-2.5 text-[#567b5d]; }.included-card b,.included-card small { @apply block; }.included-card b { @apply text-sm; }.included-card small { @apply mt-1 text-xs text-[#818881]; }.included-card button { @apply text-sm font-bold text-[#56795d]; }
.payment-dialog { @apply relative w-full max-w-[490px] rounded-[1.5rem] bg-[#fffdfa] p-6 shadow-2xl sm:p-7; }.close-button { @apply absolute right-4 top-4 rounded-lg p-2 text-[#7c847d] hover:bg-[#f1f1ec]; }.payment-heading { @apply flex items-center gap-3; }.payment-heading>span { @apply grid h-11 w-11 place-items-center rounded-xl bg-[#e5f1e5] text-[#55775c]; }.payment-heading p { @apply text-xs font-bold uppercase tracking-[.14em] text-[#718274]; }.payment-heading h2 { @apply mt-1 text-xl font-black; }.payment-summary { @apply mt-6 flex items-center justify-between rounded-xl bg-[#f3f5ef] px-4 py-3 text-sm text-[#637066]; }.payment-summary strong { @apply text-base text-[#29372e]; }.payment-summary small { @apply text-xs font-normal text-[#7d877e]; }.payment-dialog label { @apply block text-xs font-bold text-[#59655c]; }.payment-dialog input:not([type='checkbox']) { @apply mt-1.5 w-full rounded-xl border border-[#ddd9d0] bg-white px-3 py-2.5 text-sm text-[#29372e] outline-none transition placeholder:text-[#abb0aa] focus:border-[#719176] focus:ring-2 focus:ring-[#dceadc]; }.input-icon { @apply relative; }.input-icon svg { @apply absolute left-3 top-[calc(50%-2px)] h-4 w-4 -translate-y-1/2 text-[#8b948b]; }.input-icon input { @apply pl-9 !important; }.agreement { @apply flex !important items-center gap-2 text-xs font-medium !important text-[#6f776f] !important; }.agreement input { @apply h-4 w-4 accent-[#5b8263]; }.pay-button { @apply w-full rounded-xl bg-[#5b8263] py-3 text-sm font-bold text-white shadow-[0_8px_16px_rgba(76,112,83,.18)] transition hover:bg-[#4f7557] disabled:cursor-not-allowed disabled:bg-[#bdc7bb] disabled:shadow-none; }.payment-note { @apply mt-4 flex items-center justify-center gap-1 text-center text-[11px] text-[#838a83]; }
</style>
